stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/image

build_01:
  stage: build
  script:
    - cd 01-emetteurUDPv4
    - scons
  artifacts:
    paths:
      - 01-emetteurUDPv4/sender-udp

# run tests using the binary build before
test_01:
  stage: test
  needs: [build_01]
  script:
  - |
    echo "starting test"
    cd 01-emetteurUDPv4
    bash tests.sh
