stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/image

build_03:
  stage: build
  script:
    - cd 03-recepteurUDPv4
    - scons
  artifacts:
    paths:
      - 03-recepteurUDPv4/receiver-udp

# run tests using the binary build before
test_03:
  stage: test
  needs: [build_03]
  script:
  - |
    echo "starting tests"
    cd 03-recepteurUDPv4
    bash tests.sh
